# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='qr_code',
            field=models.ImageField(upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='signed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
