# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_auto_20160929_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='qr_code',
        ),
    ]
