# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_remove_file_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
