# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_auto_20160929_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
